name: lint
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Check Typescript
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: ${{ github.event_name != 'pull_request' && 'github-check' || 'github-pr-review' }}
      - name: Check Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: ${{ github.event_name != 'pull_request' && 'github-check' || 'github-pr-review' }}
      - name: Check ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: ${{ github.event_name != 'pull_request' && 'github-check' || 'github-pr-review' }}
